import type { Category, MenuItem, Order, StoreSettings } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'pizza', nameFr: 'Pizzas', nameAr: 'بيتزا', emoji: '', order: 1 },
  { id: 'burger', nameFr: 'Burgers', nameAr: 'برغر', emoji: '', order: 2 },
  { id: 'sandwich', nameFr: 'Sandwichs', nameAr: 'ساندويش', emoji: '', order: 3 },
  { id: 'boisson', nameFr: 'Boissons', nameAr: 'مشروبات', emoji: '', order: 4 },
  { id: 'dessert', nameFr: 'Desserts', nameAr: 'حلويات', emoji: '', order: 5 },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: 'p1',
    categoryId: 'pizza',
    nameFr: 'Pizza Margherita',
    nameAr: 'بيتزا مارغريتا',
    descriptionFr: 'Sauce tomate, mozzarella fraîche, basilic',
    descriptionAr: 'صلصة طماطم، موزاريلا طازجة، ريحان',
    price: 1200,
    image:
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'p2',
    categoryId: 'pizza',
    nameFr: 'Pizza Poulet Rôti',
    nameAr: 'بيتزا الدجاج المشوي',
    descriptionFr: 'Poulet rôti, poivrons, oignons, sauce crème',
    descriptionAr: 'دجاج مشوي، فلفل، بصل، صلصة كريمة',
    price: 1400,
    image:
      'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'p3',
    categoryId: 'pizza',
    nameFr: 'Pizza 4 Fromages',
    nameAr: 'بيتزا أربعة أجبان',
    descriptionFr: 'Mozzarella, emmental, chèvre, parmesan',
    descriptionAr: 'موزاريلا، إيمنتال، جبن الماعز، بارميزان',
    price: 1500,
    image:
      'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'p4',
    categoryId: 'pizza',
    nameFr: 'Pizza Végétarienne',
    nameAr: 'بيتزا نباتية',
    descriptionFr: 'Légumes grillés, sauce tomate, herbes de Provence',
    descriptionAr: 'خضروات مشوية، صلصة طماطم، أعشاب',
    price: 1100,
    image:
      'https://images.unsplash.com/photo-1511689660979-10d2b1aada49?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'b1',
    categoryId: 'burger',
    nameFr: 'Burger Classique',
    nameAr: 'برغر كلاسيك',
    descriptionFr: 'Bœuf 150g, cheddar, salade, tomate, cornichon',
    descriptionAr: 'لحم بقري 150غ، شيدر، خس، طماطم، مخلل',
    price: 800,
    image:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'b2',
    categoryId: 'burger',
    nameFr: 'Burger Poulet Crispy',
    nameAr: 'برغر الدجاج المقرمش',
    descriptionFr: 'Poulet pané croustillant, sauce ranch, coleslaw',
    descriptionAr: 'دجاج مقرمش مخبوز، صلصة رانش، سلطة',
    price: 850,
    image:
      'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'b3',
    categoryId: 'burger',
    nameFr: 'Double Smash Burger',
    nameAr: 'دبل سماش برغر',
    descriptionFr: 'Double steak smashé, double cheddar, sauce spéciale',
    descriptionAr: 'ستيك مضغوط مزدوج، شيدر مزدوج، صلصة خاصة',
    price: 950,
    image:
      'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 's1',
    categoryId: 'sandwich',
    nameFr: 'Sandwich Kefta',
    nameAr: 'ساندويش كفتة',
    descriptionFr: 'Kefta grillée, harissa, frites, salade',
    descriptionAr: 'كفتة مشوية، هريسة، بطاطس، سلطة',
    price: 450,
    image:
      'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 's2',
    categoryId: 'sandwich',
    nameFr: 'Sandwich Poulet',
    nameAr: 'ساندويش دجاج',
    descriptionFr: 'Filet de poulet grillé, fromage, légumes frais',
    descriptionAr: 'فيليه دجاج مشوي، جبن، خضروات طازجة',
    price: 500,
    image:
      'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 's3',
    categoryId: 'sandwich',
    nameFr: 'Sandwich Merguez',
    nameAr: 'ساندويش مرقاز',
    descriptionFr: 'Merguez grillée, harissa douce, tomate, oignon',
    descriptionAr: 'مرقاز مشوي، هريسة خفيفة، طماطم، بصل',
    price: 480,
    image:
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'dr1',
    categoryId: 'boisson',
    nameFr: 'Coca-Cola 33cl',
    nameAr: 'كوكا كولا 33سل',
    descriptionFr: 'Canette fraîche',
    descriptionAr: 'علبة باردة',
    price: 150,
    image:
      'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'dr2',
    categoryId: 'boisson',
    nameFr: 'Eau Minérale',
    nameAr: 'ماء معدني',
    descriptionFr: 'Bouteille 50cl',
    descriptionAr: 'قارورة 50سل',
    price: 80,
    image:
      'https://images.unsplash.com/photo-1564419320408-38e24e038c6d?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'dr3',
    categoryId: 'boisson',
    nameFr: "Jus d'Orange Frais",
    nameAr: 'عصير برتقال طازج',
    descriptionFr: 'Pressé à la commande',
    descriptionAr: 'يُعصر عند الطلب',
    price: 250,
    image:
      'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'd1',
    categoryId: 'dessert',
    nameFr: 'Tiramisu Maison',
    nameAr: 'تيراميسو منزلي',
    descriptionFr: 'Recette traditionnelle, mascarpone et café',
    descriptionAr: 'وصفة تقليدية، ماسكاربوني وقهوة',
    price: 350,
    image:
      'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
  {
    id: 'd2',
    categoryId: 'dessert',
    nameFr: 'Crêpe Nutella',
    nameAr: 'كريب نوتيلا',
    descriptionFr: 'Crêpe maison, Nutella, banane, noisettes',
    descriptionAr: 'كريب منزلي، نوتيلا، موز، بندق',
    price: 300,
    image:
      'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=1200&q=80',
    available: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'CMD-1001',
    createdAt: '2024-12-01T18:30:00Z',
    clientName: 'Mohamed Amrani',
    clientPhone: '0555 123 456',
    wilaya: 'Alger',
    commune: 'Bab El Oued',
    address: '12 Rue Didouche Mourad',
    notes: 'Sans oignons s.v.p.',
    items: [
      { name: 'Pizza Margherita', quantity: 1, price: 1200 },
      { name: 'Coca-Cola 33cl', quantity: 2, price: 300 },
    ],
    subtotal: 1500,
    deliveryFee: 200,
    total: 1700,
    status: 'nouveau',
  },
  {
    id: 'CMD-1002',
    createdAt: '2024-12-01T19:00:00Z',
    clientName: 'Fatima Benali',
    clientPhone: '0661 234 567',
    wilaya: 'Oran',
    commune: 'Hai El Badr',
    address: '45 Boulevard Colonel Lotfi',
    items: [
      { name: 'Burger Classique', quantity: 2, price: 1600 },
      { name: "Jus d'Orange Frais", quantity: 1, price: 250 },
    ],
    subtotal: 1850,
    deliveryFee: 350,
    total: 2200,
    status: 'preparation',
  },
  {
    id: 'CMD-1003',
    createdAt: '2024-12-01T17:00:00Z',
    clientName: 'Karim Belkacem',
    clientPhone: '0771 345 678',
    wilaya: 'Constantine',
    commune: 'Sidi Mabrouk',
    address: '7 Rue Larbi Ben Mhidi',
    items: [
      { name: 'Pizza 4 Fromages', quantity: 1, price: 1500 },
      { name: "Jus d'Orange Frais", quantity: 2, price: 500 },
      { name: 'Tiramisu Maison', quantity: 1, price: 350 },
    ],
    subtotal: 2350,
    deliveryFee: 350,
    total: 2700,
    status: 'livre',
  },
  {
    id: 'CMD-1004',
    createdAt: '2024-12-01T20:15:00Z',
    clientName: 'Aicha Tlemcani',
    clientPhone: '0554 456 789',
    wilaya: 'Annaba',
    commune: 'El Bouni',
    address: "23 Avenue de l'ALN",
    items: [
      { name: 'Sandwich Kefta', quantity: 3, price: 1350 },
      { name: 'Eau Minérale', quantity: 3, price: 240 },
    ],
    subtotal: 1590,
    deliveryFee: 400,
    total: 1990,
    status: 'nouveau',
  },
  {
    id: 'CMD-1005',
    createdAt: '2024-12-01T16:45:00Z',
    clientName: 'Yacine Hadj',
    clientPhone: '0662 567 890',
    wilaya: 'Tizi Ouzou',
    commune: 'Tizi Ouzou Ville',
    address: '5 Rue Abane Ramdane',
    items: [
      { name: 'Double Smash Burger', quantity: 1, price: 950 },
      { name: 'Tiramisu Maison', quantity: 1, price: 350 },
    ],
    subtotal: 1300,
    deliveryFee: 300,
    total: 1600,
    status: 'annule',
  },
];

export const ALGERIA_WILAYAS: { code: number; fr: string; ar: string; fee: number }[] = [
  { code: 16, fr: 'Alger', ar: 'الجزائر', fee: 200 },
  { code: 9, fr: 'Blida', ar: 'البليدة', fee: 250 },
  { code: 35, fr: 'Boumerdès', ar: 'بومرداس', fee: 250 },
  { code: 42, fr: 'Tipaza', ar: 'تيبازة', fee: 280 },
  { code: 44, fr: 'Aïn Defla', ar: 'عين الدفلى', fee: 300 },
  { code: 10, fr: 'Bouira', ar: 'البويرة', fee: 300 },
  { code: 15, fr: 'Tizi Ouzou', ar: 'تيزي وزو', fee: 300 },
  { code: 26, fr: 'Médéa', ar: 'المدية', fee: 320 },
  { code: 6, fr: 'Béjaïa', ar: 'بجاية', fee: 350 },
  { code: 2, fr: 'Chlef', ar: 'الشلف', fee: 350 },
  { code: 27, fr: 'Mostaganem', ar: 'مستغانم', fee: 350 },
  { code: 31, fr: 'Oran', ar: 'وهران', fee: 350 },
  { code: 38, fr: 'Tissemsilt', ar: 'تيسمسيلت', fee: 350 },
  { code: 48, fr: 'Relizane', ar: 'غليزان', fee: 350 },
  { code: 34, fr: 'Bordj Bou Arréridj', ar: 'برج بوعريريج', fee: 350 },
  { code: 43, fr: 'Mila', ar: 'ميلة', fee: 350 },
  { code: 19, fr: 'Sétif', ar: 'سطيف', fee: 350 },
  { code: 23, fr: 'Annaba', ar: 'عنابة', fee: 380 },
  { code: 25, fr: 'Constantine', ar: 'قسنطينة', fee: 380 },
  { code: 36, fr: 'El Tarf', ar: 'الطارف', fee: 380 },
  { code: 4, fr: 'Oum El Bouaghi', ar: 'أم البواقي', fee: 380 },
  { code: 5, fr: 'Batna', ar: 'باتنة', fee: 380 },
  { code: 24, fr: 'Guelma', ar: 'قالمة', fee: 380 },
  { code: 41, fr: 'Souk Ahras', ar: 'سوق أهراس', fee: 400 },
  { code: 40, fr: 'Khenchela', ar: 'خنشلة', fee: 400 },
  { code: 12, fr: 'Tébessa', ar: 'تبسة', fee: 400 },
  { code: 18, fr: 'Jijel', ar: 'جيجل', fee: 400 },
  { code: 21, fr: 'Skikda', ar: 'سكيكدة', fee: 400 },
  { code: 13, fr: 'Tlemcen', ar: 'تلمسان', fee: 400 },
  { code: 22, fr: 'Sidi Bel Abbès', ar: 'سيدي بلعباس', fee: 400 },
  { code: 29, fr: 'Mascara', ar: 'معسكر', fee: 400 },
  { code: 46, fr: 'Aïn Témouchent', ar: 'عين تيموشنت', fee: 400 },
  { code: 14, fr: 'Tiaret', ar: 'تيارت', fee: 400 },
  { code: 17, fr: 'Djelfa', ar: 'الجلفة', fee: 420 },
  { code: 45, fr: 'Naâma', ar: 'النعامة', fee: 450 },
  { code: 32, fr: 'El Bayadh', ar: 'البيض', fee: 450 },
  { code: 3, fr: 'Laghouat', ar: 'الأغواط', fee: 450 },
  { code: 20, fr: 'Saïda', ar: 'سعيدة', fee: 420 },
  { code: 8, fr: 'Béchar', ar: 'بشار', fee: 500 },
  { code: 28, fr: "M'Sila", ar: 'المسيلة', fee: 400 },
  { code: 7, fr: 'Biskra', ar: 'بسكرة', fee: 420 },
  { code: 39, fr: 'El Oued', ar: 'الوادي', fee: 480 },
  { code: 30, fr: 'Ouargla', ar: 'ورقلة', fee: 500 },
  { code: 47, fr: 'Ghardaïa', ar: 'غرداية', fee: 500 },
  { code: 1, fr: 'Adrar', ar: 'أدرار', fee: 600 },
  { code: 11, fr: 'Tamanrasset', ar: 'تمنراست', fee: 700 },
  { code: 33, fr: 'Illizi', ar: 'إليزي', fee: 700 },
  { code: 37, fr: 'Tindouf', ar: 'تندوف', fee: 700 },
  { code: 49, fr: 'Timimoun', ar: 'تيميمون', fee: 600 },
  { code: 50, fr: 'Bordj Badji Mokhtar', ar: 'برج باجي مختار', fee: 700 },
  { code: 51, fr: 'Ouled Djellal', ar: 'أولاد جلال', fee: 480 },
  { code: 52, fr: 'Béni Abbès', ar: 'بني عباس', fee: 600 },
  { code: 53, fr: 'In Salah', ar: 'عين صالح', fee: 700 },
  { code: 54, fr: 'In Guezzam', ar: 'عين قزام', fee: 800 },
  { code: 55, fr: 'Touggourt', ar: 'تقرت', fee: 500 },
  { code: 56, fr: 'Djanet', ar: 'جانت', fee: 750 },
  { code: 57, fr: "El M'Ghair", ar: 'المغير', fee: 500 },
  { code: 58, fr: 'El Meniaa', ar: 'المنيعة', fee: 600 },
];

export const STORE_SETTINGS: StoreSettings = {
  nameFr: 'Fast Food El Bahdja',
  nameAr: 'فاست فود البهجة',
  descriptionFr: 'Pizzas, burgers et sandwichs faits maison — livraison rapide à Alger et en périphérie.',
  descriptionAr: 'بيتزا، برغر وساندويش منزلية — توصيل سريع في الجزائر والضواحي.',
  logoUrl: '',
  whatsappNumber: process.env.NEXT_PUBLIC_WA_NUMBER ?? '213555123456',
  address: '12 Rue des Martyrs, Alger-Centre, Alger',
  phone: '+213 555 123 456',
  mapEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3197.5!2d3.0589!3d36.7538!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzbCsDQ1JzEzLjciTiAzwrAwMyczMi4wIkU!5e0!3m2!1sfr!2sdz!4v1',
  hours: [
    { day: 'Lundi - Jeudi', openFr: 'Ouvert', openAr: 'مفتوح', hours: '11:00 — 23:00' },
    { day: 'Vendredi', openFr: 'Ouvert', openAr: 'مفتوح', hours: '14:00 — 00:00' },
    { day: 'Samedi', openFr: 'Ouvert', openAr: 'مفتوح', hours: '11:00 — 00:00' },
    { day: 'Dimanche', openFr: 'Ouvert', openAr: 'مفتوح', hours: '11:00 — 23:00' },
  ],
};
